@startmindmap
* Идея проекта
** 1. Бизнес-анализ (BA)
*** Анализ компании
**** Описание структуры предприятия
**** Описание информационных систем
**** Описание продуктового ряда
**** Анализ потребностей
**** Формирование решения
**** Формирование функциональных требований
** 2. Системный анализ (SA)
*** Архитектура
*** Технологии
*** API Контракты
*** Физическая модель данных
@endmindmap