@startmindmap
* Идея проекта
** 1. Бизнес-анализ (BA)
*** Анализ компании
**** Описание структуры предприятие
**** Описание информационных систем
**** Описание продуктового ряда
**** Анализ потребностей
**** Формирование решения
**** Формирование функциональных требований
*** Анализ конкурентов
*** Определение ЦА
** 2. Системный анализ (SA)
*** Выбор технологии
*** Архитектура
@endmindmap