# Generated by Django 5.1.6 on 2025-03-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_externaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_templates', to='core.externaluser'),
        ),
    ]
