# Generated by Django 5.1.6 on 2025-03-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_template_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='externaluser',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='core.template'),
        ),
    ]
