# Generated by Django 5.1.6 on 2025-03-27 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_template_liked_by_externaluser_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='templates/')),
                ('preview_file', models.FileField(blank=True, null=True, upload_to='previews/')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='core.template')),
            ],
        ),
    ]
