name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd ~/diplom
            git pull origin main
            npm install
            npm run build
            cd backend
            source venv/bin/activate
            pkill -f "python manage.py runserver"
            pip install -r requirements.txt
            python manage.py migrate
            nohup python manage.py runserver 0.0.0.0:8000 &
